# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1279, 833)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.infoTab = QtWidgets.QWidget()
        self.infoTab.setObjectName("infoTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.infoTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.infoTab)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.infoTab)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.fileIdSpinBox = QtWidgets.QSpinBox(self.infoTab)
        self.fileIdSpinBox.setMaximum(65535)
        self.fileIdSpinBox.setObjectName("fileIdSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fileIdSpinBox)
        self.execWindowSpinBox = QtWidgets.QSpinBox(self.infoTab)
        self.execWindowSpinBox.setMaximum(65535)
        self.execWindowSpinBox.setObjectName("execWindowSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.execWindowSpinBox)
        self.label_3 = QtWidgets.QLabel(self.infoTab)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.enduranceSpinBox = QtWidgets.QDoubleSpinBox(self.infoTab)
        self.enduranceSpinBox.setObjectName("enduranceSpinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.enduranceSpinBox)
        self.unknownBSpinBox = QtWidgets.QSpinBox(self.infoTab)
        self.unknownBSpinBox.setMaximum(255)
        self.unknownBSpinBox.setObjectName("unknownBSpinBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.unknownBSpinBox)
        self.healthSpinBox = QtWidgets.QSpinBox(self.infoTab)
        self.healthSpinBox.setMaximum(65535)
        self.healthSpinBox.setObjectName("healthSpinBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.healthSpinBox)
        self.label_4 = QtWidgets.QLabel(self.infoTab)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.infoTab)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.infoTab)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.infoTab)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.infoTab)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.infoTab)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.infoTab)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.fwdSpeedSpinBox = QtWidgets.QDoubleSpinBox(self.infoTab)
        self.fwdSpeedSpinBox.setObjectName("fwdSpeedSpinBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.fwdSpeedSpinBox)
        self.revSpeedSpinBox = QtWidgets.QDoubleSpinBox(self.infoTab)
        self.revSpeedSpinBox.setObjectName("revSpeedSpinBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.revSpeedSpinBox)
        self.jumpSpeedSpinBox = QtWidgets.QDoubleSpinBox(self.infoTab)
        self.jumpSpeedSpinBox.setObjectName("jumpSpeedSpinBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.jumpSpeedSpinBox)
        self.fallSpeedSpinBox = QtWidgets.QDoubleSpinBox(self.infoTab)
        self.fallSpeedSpinBox.setObjectName("fallSpeedSpinBox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.fallSpeedSpinBox)
        self.label_11 = QtWidgets.QLabel(self.infoTab)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.unknownCSpinBox = QtWidgets.QSpinBox(self.infoTab)
        self.unknownCSpinBox.setMaximum(255)
        self.unknownCSpinBox.setObjectName("unknownCSpinBox")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.unknownCSpinBox)
        self.unknownDSpinBox = QtWidgets.QSpinBox(self.infoTab)
        self.unknownDSpinBox.setMaximum(255)
        self.unknownDSpinBox.setObjectName("unknownDSpinBox")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.unknownDSpinBox)
        self.gridLayout_2.addLayout(self.formLayout, 0, 1, 1, 1)
        self.tabWidget.addTab(self.infoTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_5.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.spriteTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spriteTab.sizePolicy().hasHeightForWidth())
        self.spriteTab.setSizePolicy(sizePolicy)
        self.spriteTab.setObjectName("spriteTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.spriteTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.spriteTab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.spriteTab)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.spriteTab)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton = QtWidgets.QPushButton(self.spriteTab)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.horizontalSlider = QtWidgets.QSlider(self.spriteTab)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.horizontalSlider)
        self.gridLayout_4.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_13 = QtWidgets.QLabel(self.spriteTab)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.spriteTab)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_14 = QtWidgets.QLabel(self.spriteTab)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_16 = QtWidgets.QLabel(self.spriteTab)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.spriteTab)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.spriteTab)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_18 = QtWidgets.QLabel(self.spriteTab)
        self.label_18.setObjectName("label_18")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtWidgets.QLabel(self.spriteTab)
        self.label_19.setObjectName("label_19")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.label_20 = QtWidgets.QLabel(self.spriteTab)
        self.label_20.setObjectName("label_20")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtWidgets.QLabel(self.spriteTab)
        self.label_21.setObjectName("label_21")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.label_22 = QtWidgets.QLabel(self.spriteTab)
        self.label_22.setObjectName("label_22")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.label_28 = QtWidgets.QLabel(self.spriteTab)
        self.label_28.setObjectName("label_28")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.label_29 = QtWidgets.QLabel(self.spriteTab)
        self.label_29.setObjectName("label_29")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.label_30 = QtWidgets.QLabel(self.spriteTab)
        self.label_30.setObjectName("label_30")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.label_31 = QtWidgets.QLabel(self.spriteTab)
        self.label_31.setObjectName("label_31")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.label_32 = QtWidgets.QLabel(self.spriteTab)
        self.label_32.setObjectName("label_32")
        self.formLayout_3.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.spinBox_13 = QtWidgets.QSpinBox(self.spriteTab)
        self.spinBox_13.setMaximum(65535)
        self.spinBox_13.setObjectName("spinBox_13")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox_13)
        self.spinBox_14 = QtWidgets.QSpinBox(self.spriteTab)
        self.spinBox_14.setMaximum(65535)
        self.spinBox_14.setObjectName("spinBox_14")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBox_14)
        self.spinBox_15 = QtWidgets.QSpinBox(self.spriteTab)
        self.spinBox_15.setMaximum(255)
        self.spinBox_15.setObjectName("spinBox_15")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBox_15)
        self.spinBox_16 = QtWidgets.QSpinBox(self.spriteTab)
        self.spinBox_16.setMaximum(255)
        self.spinBox_16.setObjectName("spinBox_16")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinBox_16)
        self.spinBox_17 = QtWidgets.QSpinBox(self.spriteTab)
        self.spinBox_17.setMaximum(255)
        self.spinBox_17.setObjectName("spinBox_17")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.spinBox_17)
        self.spinBox_18 = QtWidgets.QSpinBox(self.spriteTab)
        self.spinBox_18.setMaximum(255)
        self.spinBox_18.setObjectName("spinBox_18")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.spinBox_18)
        self.spinBox_19 = QtWidgets.QSpinBox(self.spriteTab)
        self.spinBox_19.setMaximum(255)
        self.spinBox_19.setObjectName("spinBox_19")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.spinBox_19)
        self.spinBox_20 = QtWidgets.QSpinBox(self.spriteTab)
        self.spinBox_20.setMaximum(255)
        self.spinBox_20.setObjectName("spinBox_20")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.spinBox_20)
        self.spinBox_21 = QtWidgets.QSpinBox(self.spriteTab)
        self.spinBox_21.setMaximum(255)
        self.spinBox_21.setObjectName("spinBox_21")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.spinBox_21)
        self.spinBox_22 = QtWidgets.QSpinBox(self.spriteTab)
        self.spinBox_22.setMaximum(255)
        self.spinBox_22.setObjectName("spinBox_22")
        self.formLayout_3.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.spinBox_22)
        self.horizontalLayout_2.addLayout(self.formLayout_3)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_12 = QtWidgets.QLabel(self.spriteTab)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_15 = QtWidgets.QLabel(self.spriteTab)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.spinBox = QtWidgets.QSpinBox(self.spriteTab)
        self.spinBox.setMaximum(255)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.spinBox_2 = QtWidgets.QSpinBox(self.spriteTab)
        self.spinBox_2.setMaximum(255)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)
        self.label_17 = QtWidgets.QLabel(self.spriteTab)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_23 = QtWidgets.QLabel(self.spriteTab)
        self.label_23.setObjectName("label_23")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.label_24 = QtWidgets.QLabel(self.spriteTab)
        self.label_24.setObjectName("label_24")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.label_25 = QtWidgets.QLabel(self.spriteTab)
        self.label_25.setObjectName("label_25")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.label_26 = QtWidgets.QLabel(self.spriteTab)
        self.label_26.setObjectName("label_26")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.label_27 = QtWidgets.QLabel(self.spriteTab)
        self.label_27.setObjectName("label_27")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.label_33 = QtWidgets.QLabel(self.spriteTab)
        self.label_33.setObjectName("label_33")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.label_34 = QtWidgets.QLabel(self.spriteTab)
        self.label_34.setObjectName("label_34")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.label_35 = QtWidgets.QLabel(self.spriteTab)
        self.label_35.setObjectName("label_35")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.label_36 = QtWidgets.QLabel(self.spriteTab)
        self.label_36.setObjectName("label_36")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.spinBox_3 = QtWidgets.QSpinBox(self.spriteTab)
        self.spinBox_3.setMaximum(255)
        self.spinBox_3.setObjectName("spinBox_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_3)
        self.spinBox_4 = QtWidgets.QSpinBox(self.spriteTab)
        self.spinBox_4.setMaximum(255)
        self.spinBox_4.setObjectName("spinBox_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox_4)
        self.spinBox_5 = QtWidgets.QSpinBox(self.spriteTab)
        self.spinBox_5.setMaximum(255)
        self.spinBox_5.setObjectName("spinBox_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBox_5)
        self.spinBox_6 = QtWidgets.QSpinBox(self.spriteTab)
        self.spinBox_6.setMaximum(255)
        self.spinBox_6.setObjectName("spinBox_6")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBox_6)
        self.spinBox_7 = QtWidgets.QSpinBox(self.spriteTab)
        self.spinBox_7.setMaximum(255)
        self.spinBox_7.setObjectName("spinBox_7")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinBox_7)
        self.spinBox_8 = QtWidgets.QSpinBox(self.spriteTab)
        self.spinBox_8.setMaximum(255)
        self.spinBox_8.setObjectName("spinBox_8")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.spinBox_8)
        self.spinBox_9 = QtWidgets.QSpinBox(self.spriteTab)
        self.spinBox_9.setMaximum(255)
        self.spinBox_9.setObjectName("spinBox_9")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.spinBox_9)
        self.spinBox_10 = QtWidgets.QSpinBox(self.spriteTab)
        self.spinBox_10.setMaximum(255)
        self.spinBox_10.setObjectName("spinBox_10")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.spinBox_10)
        self.spinBox_11 = QtWidgets.QSpinBox(self.spriteTab)
        self.spinBox_11.setMaximum(255)
        self.spinBox_11.setObjectName("spinBox_11")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.spinBox_11)
        self.spinBox_12 = QtWidgets.QSpinBox(self.spriteTab)
        self.spinBox_12.setMaximum(255)
        self.spinBox_12.setObjectName("spinBox_12")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.spinBox_12)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_37 = QtWidgets.QLabel(self.spriteTab)
        self.label_37.setObjectName("label_37")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.spinBox_23 = QtWidgets.QSpinBox(self.spriteTab)
        self.spinBox_23.setObjectName("spinBox_23")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_23)
        self.label_38 = QtWidgets.QLabel(self.spriteTab)
        self.label_38.setObjectName("label_38")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.spinBox_24 = QtWidgets.QSpinBox(self.spriteTab)
        self.spinBox_24.setObjectName("spinBox_24")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_24)
        self.label_39 = QtWidgets.QLabel(self.spriteTab)
        self.label_39.setObjectName("label_39")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.spinBox_25 = QtWidgets.QSpinBox(self.spriteTab)
        self.spinBox_25.setObjectName("spinBox_25")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_25)
        self.label_40 = QtWidgets.QLabel(self.spriteTab)
        self.label_40.setObjectName("label_40")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.checkBox = QtWidgets.QCheckBox(self.spriteTab)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkBox)
        self.horizontalLayout_3.addLayout(self.formLayout_4)
        self.graphicsView = QtWidgets.QGraphicsView(self.spriteTab)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_3.addWidget(self.graphicsView)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 2, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.spriteTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_3.addWidget(self.listWidget, 0, 0, 1, 1)
        self.listWidget_2 = QtWidgets.QListWidget(self.spriteTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_2.sizePolicy().hasHeightForWidth())
        self.listWidget_2.setSizePolicy(sizePolicy)
        self.listWidget_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout_3.addWidget(self.listWidget_2, 0, 1, 1, 1)
        self.tabWidget.addTab(self.spriteTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1279, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AF Editor"))
        self.label.setText(_translate("MainWindow", "File ID"))
        self.label_2.setText(_translate("MainWindow", "Exec Window"))
        self.label_3.setText(_translate("MainWindow", "Endurance"))
        self.label_4.setText(_translate("MainWindow", "Unknown"))
        self.label_5.setText(_translate("MainWindow", "\'Health"))
        self.label_6.setText(_translate("MainWindow", "Fwd speed"))
        self.label_7.setText(_translate("MainWindow", "Rev speed"))
        self.label_8.setText(_translate("MainWindow", "Jump speed"))
        self.label_9.setText(_translate("MainWindow", "Fall speed"))
        self.label_10.setText(_translate("MainWindow", "Unknown C"))
        self.label_11.setText(_translate("MainWindow", "Unknown D"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.infoTab), _translate("MainWindow", "Information"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Sounds"))
        self.pushButton_2.setText(_translate("MainWindow", "<<"))
        self.pushButton_3.setText(_translate("MainWindow", "Stop"))
        self.pushButton_4.setText(_translate("MainWindow", "Play"))
        self.pushButton.setText(_translate("MainWindow", ">>"))
        self.label_13.setText(_translate("MainWindow", "Move String"))
        self.label_14.setText(_translate("MainWindow", "Footer String"))
        self.label_16.setText(_translate("MainWindow", "Animation String"))
        self.label_18.setText(_translate("MainWindow", "Unknown 0"))
        self.label_19.setText(_translate("MainWindow", "Unknown 2"))
        self.label_20.setText(_translate("MainWindow", "Unknown 4"))
        self.label_21.setText(_translate("MainWindow", "Unknown 5"))
        self.label_22.setText(_translate("MainWindow", "Unknown 6"))
        self.label_28.setText(_translate("MainWindow", "Unknown 7"))
        self.label_29.setText(_translate("MainWindow", "Unknown 8"))
        self.label_30.setText(_translate("MainWindow", "Unknown 9"))
        self.label_31.setText(_translate("MainWindow", "Unknown 10"))
        self.label_32.setText(_translate("MainWindow", "Unknown 11"))
        self.label_12.setText(_translate("MainWindow", "Next Animation ID"))
        self.label_15.setText(_translate("MainWindow", "Category"))
        self.label_17.setText(_translate("MainWindow", "Unknown 14"))
        self.label_23.setText(_translate("MainWindow", "Scrap amount"))
        self.label_24.setText(_translate("MainWindow", "Successor ID"))
        self.label_25.setText(_translate("MainWindow", "Damage amount"))
        self.label_26.setText(_translate("MainWindow", "Unknown 18"))
        self.label_27.setText(_translate("MainWindow", "Unknown 19"))
        self.label_33.setText(_translate("MainWindow", "Points on hit"))
        self.label_34.setText(_translate("MainWindow", "Start X"))
        self.label_35.setText(_translate("MainWindow", "Start Y"))
        self.label_36.setText(_translate("MainWindow", "null"))
        self.label_37.setText(_translate("MainWindow", "X"))
        self.label_38.setText(_translate("MainWindow", "Y"))
        self.label_39.setText(_translate("MainWindow", "Index"))
        self.label_40.setText(_translate("MainWindow", "Missing"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.spriteTab), _translate("MainWindow", "Sprites"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Alt+F4"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As ..."))

