# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1279, 833)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.infoTab = QtWidgets.QWidget()
        self.infoTab.setObjectName("infoTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.infoTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.infoTab)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.infoTab)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.fileIdSpinBox = QtWidgets.QSpinBox(self.infoTab)
        self.fileIdSpinBox.setObjectName("fileIdSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fileIdSpinBox)
        self.execWindowSpinBox = QtWidgets.QSpinBox(self.infoTab)
        self.execWindowSpinBox.setObjectName("execWindowSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.execWindowSpinBox)
        self.label_3 = QtWidgets.QLabel(self.infoTab)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.enduranceSpinBox = QtWidgets.QDoubleSpinBox(self.infoTab)
        self.enduranceSpinBox.setObjectName("enduranceSpinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.enduranceSpinBox)
        self.unknownBSpinBox = QtWidgets.QSpinBox(self.infoTab)
        self.unknownBSpinBox.setObjectName("unknownBSpinBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.unknownBSpinBox)
        self.healthSpinBox = QtWidgets.QSpinBox(self.infoTab)
        self.healthSpinBox.setObjectName("healthSpinBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.healthSpinBox)
        self.label_4 = QtWidgets.QLabel(self.infoTab)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.infoTab)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.infoTab)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.infoTab)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.infoTab)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.infoTab)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.infoTab)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.fwdSpeedSpinBox = QtWidgets.QDoubleSpinBox(self.infoTab)
        self.fwdSpeedSpinBox.setObjectName("fwdSpeedSpinBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.fwdSpeedSpinBox)
        self.revSpeedSpinBox = QtWidgets.QDoubleSpinBox(self.infoTab)
        self.revSpeedSpinBox.setObjectName("revSpeedSpinBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.revSpeedSpinBox)
        self.jumpSpeedSpinBox = QtWidgets.QDoubleSpinBox(self.infoTab)
        self.jumpSpeedSpinBox.setObjectName("jumpSpeedSpinBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.jumpSpeedSpinBox)
        self.fallSpeedSpinBox = QtWidgets.QDoubleSpinBox(self.infoTab)
        self.fallSpeedSpinBox.setObjectName("fallSpeedSpinBox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.fallSpeedSpinBox)
        self.unknownCSpinBox = QtWidgets.QSpinBox(self.infoTab)
        self.unknownCSpinBox.setObjectName("unknownCSpinBox")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.unknownCSpinBox)
        self.gridLayout_2.addLayout(self.formLayout, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.tabWidget.addTab(self.infoTab, "")
        self.spriteTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spriteTab.sizePolicy().hasHeightForWidth())
        self.spriteTab.setSizePolicy(sizePolicy)
        self.spriteTab.setObjectName("spriteTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.spriteTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.treeView = QtWidgets.QTreeView(self.spriteTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setMaximumSize(QtCore.QSize(250, 16777215))
        self.treeView.setObjectName("treeView")
        self.gridLayout_3.addWidget(self.treeView, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.spriteTab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.spriteTab)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.spriteTab)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton = QtWidgets.QPushButton(self.spriteTab)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.horizontalSlider = QtWidgets.QSlider(self.spriteTab)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.horizontalSlider)
        self.gridLayout_4.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.spriteTab)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_4.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        self.tabWidget.addTab(self.spriteTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1279, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AF Editor"))
        self.label.setText(_translate("MainWindow", "File ID"))
        self.label_2.setText(_translate("MainWindow", "Exec Window"))
        self.label_3.setText(_translate("MainWindow", "Endurance"))
        self.label_4.setText(_translate("MainWindow", "Unknown"))
        self.label_5.setText(_translate("MainWindow", "\'Health"))
        self.label_6.setText(_translate("MainWindow", "Fwd speed"))
        self.label_7.setText(_translate("MainWindow", "Rev speed"))
        self.label_8.setText(_translate("MainWindow", "Jump speed"))
        self.label_9.setText(_translate("MainWindow", "Fall speed"))
        self.label_10.setText(_translate("MainWindow", "Unknown"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.infoTab), _translate("MainWindow", "Information"))
        self.pushButton_2.setText(_translate("MainWindow", "<<"))
        self.pushButton_3.setText(_translate("MainWindow", "Stop"))
        self.pushButton_4.setText(_translate("MainWindow", "Play"))
        self.pushButton.setText(_translate("MainWindow", ">>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.spriteTab), _translate("MainWindow", "Sprites"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Alt+F4"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As ..."))

